### ISSUE TITLE
Transitive dependency `ecstatic` (via `http-server`) is missing

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux-sdk-builder#101]
The `ecstatic` 3.x library referenced by `http-server` is no longer available via NPM, causing all consumers' builds to fail.

**Comment by Blackbaud-PaulCrowder** [comment]
https://github.com/jfhbrook/node-ecstatic/issues/255

**Comment by Blackbaud-PaulCrowder** [comment]
https://github.com/indexzero/http-server/issues/521

**Comment by thornjad** [comment]
jfhbrook/node-ecstatic#256
