### ISSUE TITLE
skyux serve does not work in IE11

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-sdk-builder#119]

**Comment by Blackbaud-SteveBrush** [comment]
Might be related: https://github.com/blackbaud/skyux-sdk-builder/blob/master/tsconfig.json#L17 versus https://github.com/blackbaud/skyux-sdk-builder/blob/master/cli/utils/run-build.js#L34

**Comment by Blackbaud-TrevorBurch** [comment]
Was able to serve in IE 11 today with builder `3.8.1`. Can reopen if we notice this happening again.
