### ISSUE TITLE
`moduleAliases` does not work for AoT builds

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-sdk-builder#121]
I get "module not found" errors for AoT builds when using the *skyuxconfig.json* setting `moduleAliases`.

It turns out that Angular's `AngularCompilerPlugin` (which we use for AoT webpack compilation) also requires the *tsconfig.json* `paths` setting to match webpack's `resolve.alias` setting.

For more info, see: https://github.com/angular/angular-cli/issues/5031#issuecomment-324844012

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.6.7`
