### ISSUE TITLE
`skyux pact` should not include code coverage analysis

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux-sdk-builder#124]
## Expected Behavior
Was not expecting setting `codeCoverageThreshold` to fail my `skyux pact` step due to having low code coverage. I was expecting that command to not do _any_ code coverage analysis. The pact tests are not meant to cover the _whole_ app, just the REST calls.

## Actual Behavior

`skyux pact` fails due to `codeCoverageThreshold`.

## Problem in real world

Here's an [internal build](https://blackbaud.visualstudio.com/Products/_build/results?buildId=724093&_a=summary) where `skyux pact` is failing due to code coverage.

Here's the relevant output:

```
SUMMARY:
√ 7 tests completed
TOTAL: 7 SUCCESS

=============================== Coverage summary ===============================
Statements   : 71.07% ( 285/401 )
Branches     : 25% ( 13/52 )
Functions    : 52.08% ( 50/96 )
Lines        : 68.5% ( 237/346 )
================================================================================
07 06 2019 15:31:57.601:ERROR [reporter.coverage-istanbul]: Coverage for statements (71.07%) does not meet global threshold (80%)
07 06 2019 15:31:57.601:ERROR [reporter.coverage-istanbul]: Coverage for lines (68.5%) does not meet global threshold (80%)
07 06 2019 15:31:57.601:ERROR [reporter.coverage-istanbul]: Coverage for branches (25%) does not meet global threshold (80%)
07 06 2019 15:31:57.601:ERROR [reporter.coverage-istanbul]: Coverage for functions (52.08%) does not meet global threshold (80%)
Karma has exited with 1.
```

## Implementation

If everyone agrees that this is in fact a bug (at least a desirable thing), then I will run with it and tweak the `shared.karma.conf.js` to reflect this. But if there is a valid reason that I'm not seeing for pact to track coverage, add to the [existing internal slack thread](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1559922505074400) so I process that and change my process accordingly.

Edit: I completely forgot that I can override `codeCoverageThreshold` in my `skyuxconfig.pact.json` (doh!), thus this doesn't block me. i can set `standard` for the project and set `none` on the pact. so this isn't has high priority for me personally anymore. so no need for me to tweak it soon. but still seems like a bug. prioritize like normal though.

**Comment by Blackbaud-SteveBrush** [comment]
Added the "Breaking change" label to designate that this will be released in the next version of SKY UX Builder.

**Comment by Blackbaud-ColbyWhite** [comment]
@Blackbaud-SteveBrush does the closing of this indicate that it will be included in the next version?
