### ISSUE TITLE
For specific platforms, remove `webdriver-manager update` + use pre-installed drivers.

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-sdk-builder#13]
In the URL repo, update the `chromeDriver` (and maybe `geckoDriver`) properties to point to the Azure Builds environment variables pointing to those locations (if they exist).

- https://github.com/angular/protractor/blob/master/lib/config.ts#L78
- https://github.com/blackbaud/skyux-sdk-builder-config/blob/master/vsts/config/protractor/protractor.conf.js
- https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md

**Comment by Blackbaud-AlexKingman** [comment]
Closing - the benefits of this change aren't necessarily worth the effort.
