### ISSUE TITLE
TypeScript warnings now block compilation/reload during `skyux serve`

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux-sdk-builder#147]
At some point between the release of 3.4.0 and 3.7.1, the TypeScript warning `TS6133: 'someVariable' is declared but its value is never read.` turned into an error that blocks the page from reloading when the developer saves a file that causes that warning. Before, the app would compile successfully and the page would reload with changes, but now compilation fails and reload is prevented.

**Comment by Blackbaud-SteveBrush** [comment]
The change occurred somewhere between these two versions: 
https://github.com/blackbaud/skyux-sdk-builder/compare/3.5.3...3.6.0
