### ISSUE TITLE
Expose property from karma.config.js so skipped test output can be suppressed

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [blackbaud/skyux-sdk-builder#153]
I'd like to be able to suppress the output of skipped tests as describe here:

https://stackoverflow.com/questions/32154275/how-to-suppress-output-for-skipped-tests-in-jasmine

**Comment by Blackbaud-SteveBrush** [comment]
This would work well as a CLI command flag, `--suppress-skipped` (or something).

**Comment by Blackbaud-JasonBodnar** [comment]
Contribution with new CLI flag: #186

**Comment by Blackbaud-BobbyEarl** [comment]
Addressed in [`3.13.0`](https://github.com/blackbaud/skyux-sdk-builder/blob/master/CHANGELOG.md#3130-2020-01-15)
