### ISSUE TITLE
Pass skyuxconfig.json `host.frameOptions` to Host

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-sdk-builder#171]
Related: https://github.com/blackbaud/skyux-sdk-builder/issues/25

**Comment by Blackbaud-BobbyEarl** [comment]
Released in [`3.14.0`](https://github.com/blackbaud/skyux-sdk-builder/blob/master/CHANGELOG.md#3140-2020-02-07)
