### ISSUE TITLE
Upgrade core-js to >= 3

### ISSUE THREAD

**Issue by Blackbaud-ThomasOrtiz** [blackbaud/skyux-sdk-builder#198]
## Explanation
core-js has recently deprecated version core-js@<3 and are recommending people to upgrade to at least 3. 

```
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

## Research
- See what potential breaking changes were introduced with core-js@3
- See if we need to make any adjustments

## Relevant Info
- [skyux-sdk-builder's package.json](https://github.com/blackbaud/skyux-sdk-builder/blob/master/package.json#L49-L51)
- [core-js's changelog](https://github.com/zloirock/core-js/blob/master/CHANGELOG.md)
- [core-js's changelog at 3.0](https://github.com/zloirock/core-js/blob/master/CHANGELOG.md#300---20190319)

**Comment by Blackbaud-SteveBrush** [comment]
This will be addressed in the next version of Builder, see: https://github.com/blackbaud/skyux-sdk-builder/pull/181
