### ISSUE TITLE
Upgrade @skyux-sdk/builder to use tree-kill@1.2.2, lodash@4.17.15

### ISSUE THREAD

**Issue by jhenderson2099** [blackbaud/skyux-sdk-builder#200]
I am currently using `@skyux-sdk/builder@3.13.0`.

When running `npm audit`, some packages are flagged with HIGH vulnerabilities.

Among these are `tree-kill` and `lodash` (both used directly or indirectly by `@skyux-sdk/builder`).  

Recommendations from `npm audit` are to:
- Run ` npm install lodash@4.17.15` to fix two vulnerabilities
- Run `npm update lodash --depth 7` to resolve 34 vulnerabilities
- Possibly update `ngtools/webpack`?  
  - @Blackbaud-SteveBrush indicates that this can't be fixed until we upgrade to the latest version of Angular
  - Path `@skyux-sdk/builder` > `@ngtools/webpack` > `tree-kill`
  - Recommendation is to use `tree-kill@1.2.2`

**Comment by Blackbaud-SteveBrush** [comment]
FYI: we are actively debugging this issue and will report back.

**Comment by Blackbaud-ThomasOrtiz** [comment]
![image](https://user-images.githubusercontent.com/35976987/73000916-9b39c300-3dcf-11ea-9e20-3437948e505d.png)
