### ISSUE TITLE
Indirect reference to `https-proxy-agent` causing high security vulnerability warning

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux-sdk-builder#22]
Installing the latest version of `@skyux-sdk/builder` causes a high vulnerability warning for package `https-proxy-agent`.  The dependency tree is as follows:

```
└─┬ @skyux-sdk/builder@3.2.2
  └─┬ protractor@5.4.2
    ├─┬ browserstack@1.5.2
    │ └── https-proxy-agent@2.2.1 
    └─┬ saucelabs@1.5.0
      └── https-proxy-agent@2.2.1 
```

**Comment by Blackbaud-BobbyEarl** [comment]
https://nodesecurity.io/advisories/593

**Comment by Blackbaud-BobbyEarl** [comment]
I posted the above link as that's what shown when running `npm audit`.  Unfortunately, the site has been down for a while, so I'm not sure what the right link should be for more information.  No one down the dependency tree shown above has released updated versions addressing the vulnerability either, at the time of this comment at least.

**Comment by Blackbaud-SteveBrush** [comment]
Addressed in: https://github.com/blackbaud/skyux-sdk-builder/pull/53
