### ISSUE TITLE
Allow exclusions for required parameters

### ISSUE THREAD

**Issue by Blackbaud-BrianBlanchard** [blackbaud/skyux-sdk-builder#252]
Skyux should provide the ability to take a list of URIs to exclude for the required parameter check.  

Our issue is that we're authenticating with Microsoft OAuth and for security reasons, Microsoft won't allow any query string parameter in the redirect URI.  So what happens is the user logs in with a prompt from Microsoft in a new window and is redirected to successfully to our back to our SPA, where our SPA will grab the token from the window.  Unfortunately, the user is presented with the splash screen to choose an environment id since the envId is missing, but its both not needed and can't be provided.

We'd like to continue to use the environment ID selector if its not provided, but it seems reasonable that there will be some forms/modals (like this one), where its can't be provided or isn't necessary.

**Comment by Blackbaud-SteveBrush** [comment]
Thanks for filing an issue! Our general guidance is to create a different SPA for the pages that have different URL parameter requirements.
