### ISSUE TITLE
HTML is cacheable

### ISSUE THREAD

**Issue by Blackbaud-JaminQuimby** [blackbaud/skyux-sdk-builder#26]
Post Build Process - Service Worker Pre-cache for App Shell

Serving local static resources cache-first means that one can get all the crucial scaffolding for our SkyUX2 web app - The App Shell—on the screen without having to wait for any network responses.

### Expected behavior
1. Enable everyone to participate in the ecosystem of good!
2. Enable instant loading of our app shells: on, offline, or in high latency environments. 
3. Reduce network, cpu, I/O, memory usage of servers and increase load times

### Actual behavior
Online - App downloads from servers.
Offline - App does not load.
Latency - App takes a long time to load or will timeout.

### Steps to reproduce
Emulate a network disconnection or latency in chrome tools. 

### Resources
Service Worker Precache 
https://github.com/GoogleChrome/sw-precache#wrappers-and-starter-kits
Webpack Plugin for sw-precache
https://www.npmjs.com/package/sw-precache-webpack-plugin
Working SkyUX 2 Example
https://github.com/Blackbaud-JaminQuimby/OTG2017

**Comment by Blackbaud-AlexKingman** [comment]
As Angular CLI and SKY CLI converge, we expect to possibly pick this up for free. We will investigate more on this at that time. Closing for now.
