### ISSUE TITLE
Add support to include comments in skyuxconfig JSON files

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-sdk-builder#269]
While JSON doesn't support comments since it was originally created for passing data, its increased use for configuration files has left a need to support comments in JSON. Other tools like VSCode's config file support comments and use a special JSON with Comments parser to allow for comments in their config files. This is useful for commenting properties for the config files, providing a commented template as part of a new project template to give clues for new developers, and to temporarily comment out properties for local testing purposes.

**Comment by Blackbaud-PaulCrowder** [comment]
@Blackbaud-ScottFreeman Thanks for the PR. Unfortunately it's impractical to add this functionality since there are many other places where we read `skyuxconfig.json` server-side that would no longer function if comments were introduced into this file. Closing for now.
