### ISSUE TITLE
Explore fixing coverage reports after screenshots that are automatically committed back

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-sdk-builder#28]
Baseline screenshots are automatically committed back with `[ci skip]` in the commit message.  This is fine, but because of the skip, a code coverage report is not uploaded (since the commit does not run in Travis.

This means a pull request branched from this commit with cause codedov to display an error saying "No report found to compare against."

We should explore fixing this as it happens frequently enough to be annoying.  FYI, this behavior also happens in SKY UX, even more frequently, since `dist/` is committed back.

**Comment by Blackbaud-SteveBrush** [comment]
Closing until (if) we create an approved process for creating SKY UX SPAs and libraries.
