### ISSUE TITLE
Prevent coverage of Angular class constructors

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-sdk-builder#31]
### Expected behavior

Code coverage should not care about Angular class constructors.

### Actual behavior

Report mentions that constructor branch not covered.

![screen_shot_2017-07-18_at_1 16 32_pm](https://user-images.githubusercontent.com/12497062/28330678-76500dc0-6bbc-11e7-9705-87469a9f263b.png)

**Comment by Blackbaud-SteveBrush** [comment]
We'll more than likely need to migrate to using nyc instead.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.6.0`
