### ISSUE TITLE
frameOptions.urls doesn't accept wildcard port numbers

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux-sdk-builder#333]
According to the [CSP description](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors):
>The site's address may include an optional leading wildcard (the asterisk character, '*'), and you may use a wildcard (again, '*') as the port number, indicating that all legal ports are valid for the source.

Thus a site of `https://localhost:*` would be valid. however, specifying that in `skyuxconfig.json`'s `host.frameOptions.urls` prevents the SPA from rendering, instead a _Invalid frame options._ error is shown. [the logic in host](https://dev.azure.com/blackbaud/Products/_git/skyux-host?path=%2Fsrc%2FBlackbaud.SkyUX.Host%2FMiddleware%2FContextProcessorMiddleware.cs&version=GBmaster&line=218&lineEnd=219&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) that determines that url is invalid isn't clear to me, but appears to misjudge this url.

this affects the local dev scenario of
- serving SPA A via localhost (as opposed to `h.n.bb.com`)
- attempting to embed SPA B into SPA A

temporarily specifying `localhost:*` in `host.frameOptions.urls` for local dev proves problematic. this can be worked around via specifying the port, but the second you kill one of the SPAs the port will change on you, which means you will have to kill the SPA and reserve with the hardcoded port which in itselfs will reset a port so you have to start them in a specific order to keep the port numbers right.

this doesn't seem to be a builder issue, but a host issue, but i'm not sure where to put the ticket.

**Comment by Blackbaud-TerryHelems** [comment]
Internal issue filed with Host.
