### ISSUE TITLE
Static asset references cause 404 warnings to be printed during unit test runs

### ISSUE THREAD

**Issue by Blackbaud-JeffDye** [blackbaud/skyux-sdk-builder#34]
### Steps to reproduce
Write a unit test for a component whose template references a skyux static asset. Whenever running a test against that component, a warning like the following is printed in the middle of the test summaries, once per test per static asset:
```
19 07 2017 13:48:07.858:WARN [web-server]: 404: /~/assets/images/<image>.png
```
### Expected Behavior
Warnings are suppressed or do not show.

**Comment by Blackbaud-BobbyEarl** [comment]
Released in [`3.15.1`](https://github.com/blackbaud/skyux-sdk-builder/blob/master/CHANGELOG.md#3151-2020-02-20)
