### ISSUE TITLE
Add support for webpack DllPlugin/DllReferencePlugin usage.

### ISSUE THREAD

**Issue by BBCarlosMarin** [blackbaud/skyux-sdk-builder#345]
I'd like to see support for **webpack DllPlugin/DllReferencePlugin** when utilizing the `skyux serve` command as it would aid developers with decreased build times while developing SPAs.

I've done some local testing of a skyux-spa project and found that it dramatically speeds up build times by reference dll.js files created local prior to running skyux serve. However, I ran into a snag with the webpack configurations found within skyux-builder (common.webpack.config/serve.webpack.config) so I could not continue testing.

If this gains any traction, I have documentation/code showing how to get dlls injected into our SPAs.

Thanks for considering this feature/functionality!

**Comment by Blackbaud-AshleyGabriel** [comment]
SKY UX is doing work to move to Angular CLI and will not address this issue. Thanks!
