### ISSUE TITLE
pact.karma.conf.js does not support all available pact-foundation/pact-js options

### ISSUE THREAD

**Issue by jhenderson2099** [blackbaud/skyux-sdk-builder#43]
# Summary
There are several `PactOptions` within pact-js that are **not** available for use within `skyuxconfig.pact.json`.

## Available, Working Pact Server Options
Currently, the following [`skyuxconfig.pact.json` options](https://developer.blackbaud.com/skyux/learn/reference/configuration#pacts) used by the mock provider service (`pact-js`) are also supported within the `pacts` property used by [`skyux-sdk-builder`](https://github.com/blackbaud/skyux-sdk-builder/blob/8e51f262ace030e6d3f911f579288f1d74acad78/config/karma/pact.karma.conf.js):
- `consumer`
- `dir`
- `host`
- `log` 
- `logLevel`
- `port`
- `provider`
- `spec`

## Undocumented, Working Pact Server Options
The following properties [used by the mock provider service (`pact-js`)](https://github.com/pact-foundation/pact-js/blob/b83f2db8751b04f5a2f2919e46ea88e13a9df10f/src/dsl/options.ts) appear to be supported within [`pact.karma.conf.js`](https://github.com/blackbaud/skyux-sdk-builder/blob/8e51f262ace030e6d3f911f579288f1d74acad78/config/karma/pact.karma.conf.js) but are **not documented**:
- `pactFileWriteMode`

The following properties [used by the mock provider service (`pact-js`)](https://github.com/pact-foundation/pact-js/blob/b83f2db8751b04f5a2f2919e46ea88e13a9df10f/src/dsl/options.ts), but **do not appear to be supported** within [`pact.karma.conf.js`](https://github.com/blackbaud/skyux-sdk-builder/blob/8e51f262ace030e6d3f911f579288f1d74acad78/config/karma/pact.karma.conf.js), are **not documented**, but **appear to work**
- `cors`

## Undocumented, Non-Working (?) Pact Server Options
The following properties the [used by the mock provider service (`pact-js`)](https://github.com/pact-foundation/pact-js/blob/b83f2db8751b04f5a2f2919e46ea88e13a9df10f/src/dsl/options.ts), are not supported within [`pact.karma.conf.js`](https://github.com/blackbaud/skyux-sdk-builder/blob/8e51f262ace030e6d3f911f579288f1d74acad78/config/karma/pact.karma.conf.js), are **not documented, and do not work**
- `ssl`
- `sslcert`
- `sslkey`

Using `ssl` in conjunction with an HTTPS URL (but no `sslcert` or `sslkey`) results in a test failure of which the following cryptic message is displayed:
```
  Pact Binary Error: ........++++++
    ........++++++
```

Using the following settings:
```
      "ssl": true,
      "sslcert": "./node_modules/@blackbaud/skyux-builder/ssl/server.crt",
      "sslkey": "./node_modules/@blackbaud/skyux-builder/ssl/server.key"
```
with an _HTTPS_ URL, then the Pact server generates the following error

or

```
      "ssl": false,
      "sslcert": "./node_modules/@blackbaud/skyux-builder/ssl/server.crt",
      "sslkey": "./node_modules/@blackbaud/skyux-builder/ssl/server.key"
```
with an _HTTP_ URL, then the Pact server generates the following error

```
ERROR: 'Unhandled Promise rejection:', 'Unable to connect to "**http**://localhost:8106/interactions"
```

If I omit the `ssl` property or use a `false` value and keep the URL as HTTP, then the Pact test runs without issue.

**Note:**  According to the pact-js code, `ssl` is part of the `MandatoryPactOptions` interface.

The SSL option was supported as part of the e2e Pact testing setup.  Please refer to EDU Academic Qualification SPA, where the following SSL configuration works as part of Pact testing [(`k12-web-api.ts`)](https://blackbaud.visualstudio.com/Products/_git/skyux-spa-sis-academic-qualification?path=%2Fe2e%2Fsteps%2Fpact%2Fk12-web-api.ts&version=GBmaster):
```
const provider = pact({
  consumer: 'skyux-spa-sis-academic-qualification',
  provider: 'k12-legacy-api',
  port: 44353,
  **ssl: true,**
  **sslcert: path.resolve(process.cwd(), 'node_modules/@blackbaud/skyux-builder/ssl', 'server.crt'),**
  **sslkey: path.resolve(process.cwd(), 'node_modules/@blackbaud/skyux-builder/ssl', 'server.key'),**
  log: path.resolve(process.cwd(), 'logs', 'k12-web-api.log'),
  dir: path.resolve(process.cwd(), 'pacts'),
  logLevel: 'DEBUG',
  spec: 1
});
```

# References
- [https://developer.blackbaud.com/skyux/learn/reference/configuration#pacts](https://developer.blackbaud.com/skyux/learn/reference/configuration#pacts)
-  [https://github.com/blackbaud/skyux-sdk-builder/blob/8e51f262ace030e6d3f911f579288f1d74acad78/config/karma/pact.karma.conf.js](https://github.com/blackbaud/skyux-sdk-builder/blob/8e51f262ace030e6d3f911f579288f1d74acad78/config/karma/pact.karma.conf.js)
- (https://github.com/pact-foundation/pact-js/blob/b83f2db8751b04f5a2f2919e46ea88e13a9df10f/src/dsl/options.ts)[https://github.com/pact-foundation/pact-js/blob/b83f2db8751b04f5a2f2919e46ea88e13a9df10f/src/dsl/options.ts]
- (https://blackbaud.visualstudio.com/Products/_git/skyux-spa-sis-academic-qualification?path=%2Fe2e%2Fsteps%2Fpact%2Fk12-web-api.ts&version=GBmaster)[https://blackbaud.visualstudio.com/Products/_git/skyux-spa-sis-academic-qualification?path=%2Fe2e%2Fsteps%2Fpact%2Fk12-web-api.ts&version=GBmaster]

**Comment by Blackbaud-BobbyEarl** [comment]
Hey @jhenderson2099... @Blackbaud-SteveBrush is working to separate pact functionality in to its own plugin.

See:
- https://github.com/blackbaud/skyux-sdk-builder-plugin-pact/pull/1
- https://github.com/blackbaud/skyux-sdk-builder/pull/224

Can you articulate the solution for this issue and can it be applied to https://github.com/blackbaud/skyux-sdk-builder-plugin-pact/pull/1/files?

**Comment by Blackbaud-AlexKingman** [comment]
@jhenderson2099 thank you for this thorough writeup! The references were a big help.

We spent some time looking into this and it seems there's two separate issues here:
1. The docs could use some improvement.
2. SSL mock providers do not appear to be supported.

We've broken down this work into two separate issues and created a new home for each in their respective repos: 
- https://github.com/blackbaud/skyux2-docs/issues/293
- https://github.com/blackbaud/skyux-sdk-builder-plugin-pact/issues/2

Now that your info is linked and catalogued, I'm going to close this particular issue. Please follow the other two for future updates.

Thanks again for the great explanation!
