### ISSUE TITLE
Generate command overwrites existing files

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-sdk-builder#60]
If you type `skyux generate component xxx`, it will overwrite existing files.

**Comment by Blackbaud-BobbyEarl** [comment]
This was addressed in https://github.com/blackbaud/skyux-sdk-builder/commit/e29d5a330d6f8a97028fd2536b91eeba96d77969#diff-863246969ea8d79dad4d767063e98f98 and documented with https://github.com/blackbaud/skyux2-docs/pull/207
