### ISSUE TITLE
Add a step to `skyux build` to verify all resource files have the same keys

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-sdk-builder#93]
It is important that all resource files provided for a SPA (e.g. resources_en_US.json) have the same exact resource keys.  Otherwise, a user would end up missing localized text if the key was missing in the user's locale.  Managing these resource files is currently a manual process so it could be easy for someone to accidentally forget to update a file.

`skyux build` should have a step to ensure that all of these files contain the same keys in order to help catch these localization bugs before they are released (preferably committed).

**Comment by Blackbaud-BobbyEarl** [comment]
In doing some initial research, I noticed some discrepancies in the locale files that are generated.  For whomever takes on this take, make sure you take a look at https://github.com/blackbaud/skyux-sdk-builder/blob/master/lib/locale-assets-processor.js.  This will be an opportunity to make this behavior consistent.

**Comment by Blackbaud-BobbyEarl** [comment]
This functionality has been initially created as a plugin from a OTG project.  https://github.com/blackbaud/skyux-builder-resource-linter

There are a few outstanding decisions we should reach:

- Should we re-release this under the `@skyux` NPM scope.
- Should we incorporate it in to a SPAs build pipeline.
- Should we include this automatically in one of the other commands.

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-MitchellThomas owns the plugin that's providing this functionality.  https://github.com/blackbaud/skyux-builder-resource-linter

I still think a plugin is the right location for this logic.

I'm going to close this issue.  If there is still a strong interest, we can create a Work Item to add this plugin to our pipelines.
