### ISSUE TITLE
Safari 12 on BrowserStack is never captured during unit tests

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-sdk-builder#99]
Seeing this in `skyux test` unit tests logs:

```
25 04 2019 21:21:46.295:WARN [launcher.browserstack]: Safari (OS X High Sierra) has not captured in 600000 ms, killing.
```

Probably related to Safari 12 requiring users to give permission when opening an HTML file (in this case, Karma is requesting that Safari launch an HTML file to run the unit test).
See related issue: https://github.com/karma-runner/karma-safari-launcher/issues/29

**Comment by Blackbaud-BobbyEarl** [comment]
Looks like several users have a successful recommendation of pivoting to `karma-safarinative-launcher` in https://github.com/karma-runner/karma-safari-launcher/issues/29
